version: "3.7"

services:

  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - cars-db
    environment:
      - JAVA_OPTS= -Xms256M -Xmx512M

  cars-db:
    image: mysql:5
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lesson-15

volumes:
  mysql-db: